version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: practice
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  adminer:
    image: adminer
    ports:
      - '33060:8080'
